# (c) 2026 JFrog Ltd.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jfrog-evidence-opa-provider
  namespace: gatekeeper-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jfrog-evidence-opa-provider
  namespace: gatekeeper-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["jfrog-provider-content-checks"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jfrog-evidence-opa-provider
  namespace: gatekeeper-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jfrog-evidence-opa-provider
subjects:
  - kind: ServiceAccount
    name: jfrog-evidence-opa-provider
    namespace: gatekeeper-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfrog-evidence-opa-provider
  namespace: gatekeeper-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jfrog-evidence-opa-provider
  template:
    metadata:
      labels:
        run: jfrog-evidence-opa-provider
    spec:
      serviceAccountName: jfrog-evidence-opa-provider
      containers:
      - image: provider:0.2
        imagePullPolicy: IfNotPresent
        name: jfrog-evidence-opa-provider
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false 
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
          - name: jfrog-ca-cert
            mountPath: /tmp/jfrog
            readOnly: true
          - name: gatekeeper-ca-cert
            mountPath: /tmp/gatekeeper
            readOnly: true
        env:
        - name: DEBUG
          value: "true"
        - name: JFROG_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: jfrog-token-secret
              key: token
      volumes:
        - name: gatekeeper-ca-cert
          secret:
            secretName: gatekeeper-webhook-server-cert
            items:
              - key: ca.crt
                path: ca.crt
        - name: jfrog-ca-cert
          secret:
            secretName: jfrog-provider-tls
            items:
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
---
apiVersion: v1
kind: Service
metadata:
  name: jfrog-evidence-opa-provider
  namespace: gatekeeper-system
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    run: jfrog-evidence-opa-provider
  sessionAffinity: None